### ISSUE TITLE
Problem parsing null values

### ISSUE THREAD

**Issue by kattunga** [ahausladen/JsonDataObjects#11]
Hi, when you parse a Json string, null values are stored as jdtObject instead of jdtNone.

Can be reproduced with following code:
```
procedure TForm2.Button2Click(Sender: TObject);
var
  doc: TJsonObject;
begin
  doc := TJsonObject.Create;
  try
    doc.FromJSON('{"ferrcod": 2, "ferrmsg": null, "ferrval": "pepe"}');
    if doc['ferrmsg'].Typ <> jdtNone then
      raise Exception.Create('Why???');
  finally
    doc.Free;
  end;
end;
```

This doesn't happen when values are assigned one by one:
```
procedure TForm2.Button2Click(Sender: TObject);
var
  doc: TJsonObject;
begin
  doc := TJsonObject.Create;
  try
    doc['ferrcod'] := 2;
    doc['ferrmsg'] := null;
    doc['ferrval'] := "pepe";

    if doc['ferrmsg'].Typ = jdtNone then
      raise Exception.Create('Now its ok');
  finally
    doc.Free;
  end;
end;
```

**Comment by ahausladen** [comment]
jdtNone tells you that the item doesn't exist. So "Variant-Null" has to become "fdtObject:nil" if it is stored. The bug is that the Variant implementation handles varEmpty and varNull the wrong way. varEmpty.
I'll fix the variant implementation so that it returns "Unassigned" if the item doesn't exist (Typ=jdtNone) and "Null" if it is jdtObject:nil. Setting "Null" changes the value to "jdtObject:nil" and setting "Unassigned" raises an EJsonCastException.

**Comment by kattunga** [comment]
Sorry, I was not correctly understanding the meaning of jdtNone.

**Comment by ahausladen** [comment]
You found a bug anyhow.
